webtalk_init -webtalk_dir F:/Xilinx/user/vivado/heap_2_clk/heap_2_clk.sim/sim_1/behav/xsim/xsim.dir/heap_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May  4 15:22:18 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9a259ad6-4cc8-474f-82de-c36af39a4c60" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9eb8bdaae4ed4aa989da2a83788b9686" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "348" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "21370 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.38_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13064_KB" -context "xsim\\usage"
webtalk_transmit -clientid 724250335 -regid "" -xml F:/Xilinx/user/vivado/heap_2_clk/heap_2_clk.sim/sim_1/behav/xsim/xsim.dir/heap_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Xilinx/user/vivado/heap_2_clk/heap_2_clk.sim/sim_1/behav/xsim/xsim.dir/heap_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Xilinx/user/vivado/heap_2_clk/heap_2_clk.sim/sim_1/behav/xsim/xsim.dir/heap_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
