######################################################################
#
# File name : heap_tb_compile.do
# Created on: Sat Apr 17 16:41:21 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modeltech64_2019.4\\win64\\vlib modelsim_lib/work
F:\\modeltech64_2019.4\\win64\\vlib modelsim_lib/msim

F:\\modeltech64_2019.4\\win64\\vlib modelsim_lib/msim/xpm
F:\\modeltech64_2019.4\\win64\\vlib modelsim_lib/msim/fifo_generator_v13_2_5
F:\\modeltech64_2019.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modeltech64_2019.4\\win64\\vmap xpm modelsim_lib/msim/xpm
F:\\modeltech64_2019.4\\win64\\vmap fifo_generator_v13_2_5 modelsim_lib/msim/fifo_generator_v13_2_5
F:\\modeltech64_2019.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modeltech64_2019.4\\win64\\vlog  -incr -sv -work xpm  \
"F:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"F:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

F:\\modeltech64_2019.4\\win64\\vcom  -93 -work xpm  \
"F:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \

F:\\modeltech64_2019.4\\win64\\vlog  -incr -work fifo_generator_v13_2_5  \
"../../../../heap_with_fifo.ip_user_files/ipstatic/simulation/fifo_generator_vlog_beh.v" \

F:\\modeltech64_2019.4\\win64\\vcom  -93 -work fifo_generator_v13_2_5  \
"../../../../heap_with_fifo.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.vhd" \

F:\\modeltech64_2019.4\\win64\\vlog  -incr -work fifo_generator_v13_2_5  \
"../../../../heap_with_fifo.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.v" \

F:\\modeltech64_2019.4\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../heap_with_fifo.gen/sources_1/ip/fifo_generator_0/sim/fifo_generator_0.v" \
"../../../../heap_with_fifo.srcs/sources_1/imports/bram_baseline/bram_rtl.v" \
"../../../../heap_with_fifo.srcs/sources_1/imports/bram_baseline/data_store.v" \
"../../../../heap_with_fifo.srcs/sources_1/imports/bram_baseline/sort_node.v" \
"../../../../heap_with_fifo.srcs/sources_1/imports/bram_baseline/sub_heap.v" \
"../../../../heap_with_fifo.srcs/sources_1/imports/bram_baseline/heap_rtl.v" \
"../../../../heap_with_fifo.srcs/sim_1/imports/bram_baseline/heap_tb.v" \

# compile glbl module
F:\\modeltech64_2019.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

