######################################################################
#
# File name : heap_tb_wave.do
# Created on: Sun Apr 11 17:55:56 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
