######################################################################
#
# File name : heap_tb_simulate.do
# Created on: Fri Apr 16 17:10:29 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L fifo_generator_v13_2_5 -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.heap_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {heap_tb_wave.do}

view wave
view structure
view signals

do {heap_tb.udo}

run 1000ns
