@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue May 04 15:20:51 +0800 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim heap_tb_behav -key {Behavioral:sim_1:Functional:heap_tb} -tclbatch heap_tb.tcl -view F:/Xilinx/user/vivado/heap_2_clk/heap_2_clk.srcs/sim_1/imports/heap_2_clk/heap_tb_behav4.wcfg -log simulate.log"
call xsim  heap_tb_behav -key {Behavioral:sim_1:Functional:heap_tb} -tclbatch heap_tb.tcl -view F:/Xilinx/user/vivado/heap_2_clk/heap_2_clk.srcs/sim_1/imports/heap_2_clk/heap_tb_behav4.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
